# 1. URL kết nối (Lưu ý: Phải có chữ jdbc: ở đầu)
spring.datasource.url=jdbc:postgresql://anh-kiet-database-tanganhkiet09112005-965b.c.aivencloud.com:10932/defaultdb?sslmode=require

# 2. Tên đăng nhập
spring.datasource.username=avnadmin

# 3. Mật khẩu (Sử dụng biến môi trường để bảo mật)
spring.datasource.password=${DB_PASSWORD}

# 4. Driver và Dialect dành riêng cho PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Tự động cập nhật cấu trúc bảng (Cực kỳ quan trọng để Java tự tạo bảng trên Cloud)
# Cho phép Hibernate tự động sửa đổi cấu trúc bảng khi thấy code thay đổi
spring.jpa.hibernate.ddl-auto=update

# (Tùy chọn) Hiện lệnh SQL ra console để Sếp dễ theo dõi quá trình nó ALTER TABLE
spring.jpa.show-sql=true

# 6. Cho phép nhận diện IP mạng (Giúp điện thoại truy cập được)
server.address=0.0.0.0
#server.servlet.context-path=/api
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email_cua_sep@gmail.com
spring.mail.password=mat_khau_ung-dung_gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ==========================================
# CẤU HÌNH GỬI EMAIL (PAYSHARE NOTIFICATIONS)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Điền email thật của Sếp vào đây


# Các cài đặt bảo mật bắt buộc của Google SMTP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.username=email_cua_sep@gmail.com 
spring.mail.password=16_ky_tu_vua_tao_viet_lien

# ==========================================
# CẤU HÌNH GỬI EMAIL (PAYSHARE NOTIFICATIONS)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Điền đúng email mà Sếp vừa dùng để tạo mật khẩu ứng dụng
spring.mail.username=email_cua_sep@gmail.com 

# Dán 16 ký tự vào đây (VIẾT LIỀN TÙ TÌ, KHÔNG CÓ KHOẢNG TRẮNG)
spring.mail.password=abcdefghijklmnop 

# Các cài đặt bảo mật bắt buộc
