# 1. URL kết nối (Lưu ý: Phải có chữ jdbc: ở đầu)
spring.datasource.url=jdbc:postgresql://anh-kiet-database-tanganhkiet09112005-965b.c.aivencloud.com:10932/defaultdb?sslmode=require

# 2. Tên đăng nhập
spring.datasource.username=avnadmin

# 3. Mật khẩu (Sử dụng biến môi trường để bảo mật)
spring.datasource.password=${DB_PASSWORD}

# 4. Driver và Dialect dành riêng cho PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Tự động cập nhật cấu trúc bảng (Cực kỳ quan trọng để Java tự tạo bảng trên Cloud)
# Cho phép Hibernate tự động sửa đổi cấu trúc bảng khi thấy code thay đổi
spring.jpa.hibernate.ddl-auto=update

# (Tùy chọn) Hiện lệnh SQL ra console để Sếp dễ theo dõi quá trình nó ALTER TABLE
spring.jpa.show-sql=true
# 6. Cho phép nhận diện IP mạng (Giúp điện thoại truy cập được)
server.address=0.0.0.0
#server.servlet.context-path=/api
