# ==========================================
# CẤU HÌNH DATABASE (POSTGRESQL AIVEN)
# ==========================================
spring.datasource.url=jdbc:postgresql://anh-kiet-database-tanganhkiet09112005-965b.c.aivencloud.com:10932/defaultdb?sslmode=require
spring.datasource.username=avnadmin
# Sử dụng biến môi trường để bảo mật khi đẩy lên GitHub
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.address=0.0.0.0

# ==========================================
# CẤU HÌNH GỬI EMAIL (PAYSHARE NOTIFICATIONS)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# THAY BẰNG EMAIL THẬT CỦA SẾP VÀO ĐÂY (Vd: anhkiet@gmail.com)
spring.mail.username=email_cua_sep@gmail.com 

# BẢO MẬT: Dùng biến môi trường để không lộ mật khẩu 16 ký tự lên GitHub
spring.mail.password=${MAIL_PASSWORD}

# Các cài đặt bảo mật bắt buộc của Google SMTP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000